### ISSUE TITLE
Playlist lag on Play Now

### ISSUE THREAD

**Issue by JEBelcher** [bugatsinho/bugatsinho.github.io#46] opened 2020-01-25 11:40 UTC
When using Play Now, the playlist on my Android 9 box with Kodi 18.5 takes ages and then eventually plays a random track. 

Using - plugin.audio.mp3streams-2019.09.30

I'm looking at the source and will try on differnt platforms.

**Comment by JEBelcher** [comment] 2020-01-27 14:26
Same problem on Windows.

**Comment by bugatsinho** [comment] 2020-01-28 15:39
I don't like people that don't give time to check the issues.
Duplicate of #7

**Closed by bugatsinho** 2020-01-28 15:39 UTC

**Comment by JEBelcher** [comment] 2020-01-28 16:09
Sorry if I offended you.  But it is a different issue in that it dosen't hang, just takes a very long time to crate the playlist.

**Comment by bugatsinho** [comment] 2020-01-28 16:12
did you notice that I'm not supporting the addon for a long time now? so why to create an issue for it?
