### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Condottiero1** [bugatsinho/bugatsinho.github.io#25] opened 2019-09-24 15:01 UTC
Portion of log with error. I tried to attach full log but kept getting errors.."we can't process".
Install is Windows 10, Kodi18.4. It was working, then at some point asked for RMTP and another file to be enabled. They were downloaded and enabled but the addon no longer works. Thank you for your assistance.

2019-09-24 10:25:55.926 T:72196   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.sport365.live/?ex_link=http%3a%2f%2fwww.sport365.sx%2fen%2flinks%2f5d89ec11dc4e4523183722%2f1%40%5b%5d&foldername=%5bCOLOR%20lightgreen%5d%e2%80%a2%5b%2fCOLOR%5d09%3a30%3a%20%5bCOLOR%20blue%5dFC%20UTA%20Arad%20-%20FC%20Dinamo%20Bucuresti%5b%2fCOLOR%5d%20%5bCOLOR%20gold%5dRomanian-HQ%5b%2fCOLOR%5d%2c%20Soccer%20Romania%20-%20Romanian%20Cup&mode=get_streams_play&params=%7b%27_service%27%3a%20%27sport365%27%2c%20%27_act%27%3a%20%27ListChannels%27%2c%20%27_url%27%3a%20%27http%3a%2f%2fwww.sport365.sx%2f%27%2c%20%27title%27%3a%20%27%5bCOLOR%20lightgreen%5d%5cxe2%5cx80%5cxa2%5b%2fCOLOR%5d09%3a30%3a%20%5bCOLOR%20blue%5dFC%20UTA%20Arad%20-%20FC%20Dinamo%20Bucuresti%5b%2fCOLOR%5d%20%5bCOLOR%20gold%5dRomanian-HQ%5b%2fCOLOR%5d%2c%20Soccer%20Romania%20-%20Romanian%20Cup%27%7d
2019-09-24 10:25:55.941 T:70784   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sport365.live/?ex_link=http%3a%2f%2fwww.sport365.sx%2fen%2flinks%2f5d89ec11dc4e4523183722%2f1%40%5b%5d&foldername=%5bCOLOR%20lightgreen%5d%e2%80%a2%5b%2fCOLOR%5d09%3a30%3a%20%5bCOLOR%20blue%5dFC%20UTA%20Arad%20-%20FC%20Dinamo%20Bucuresti%5b%2fCOLOR%5d%20%5bCOLOR%20gold%5dRomanian-HQ%5b%2fCOLOR%5d%2c%20Soccer%20Romania%20-%20Romanian%20Cup&mode=get_streams_play&params=%7b%27_service%27%3a%20%27sport365%27%2c%20%27_act%27%3a%20%27ListChannels%27%2c%20%27_url%27%3a%20%27http%3a%2f%2fwww.sport365.sx%2f%27%2c%20%27title%27%3a%20%27%5bCOLOR%20lightgreen%5d%5cxe2%5cx80%5cxa2%5b%2fCOLOR%5d09%3a30%3a%20%5bCOLOR%20blue%5dFC%20UTA%20Arad%20-%20FC%20Dinamo%20Bucuresti%5b%2fCOLOR%5d%20%5bCOLOR%20gold%5dRomanian-HQ%5b%2fCOLOR%5d%2c%20Soccer%20Romania%20-%20Romanian%20Cup%27%7d) failed

**Comment by bugatsinho** [comment] 2019-09-24 15:03
Duplicate of #24

**Closed by bugatsinho** 2019-09-24 15:03 UTC
