### ISSUE TITLE
No links showing v2.6.3.1

### ISSUE THREAD

**Issue by ant-thomas** [bugatsinho/bugatsinho.github.io#26] opened 2019-09-28 10:05 UTC
Running Libreelec 9.1.502
List of events show, but when clicking on one there's no links available for anything.

A simple fix or config problem at my end?

**Comment by bugatsinho** [comment] 2019-09-28 14:01
next time plz take time to check if there is already an issue opened for that! thank you

Duplicate of #24

**Closed by bugatsinho** 2019-09-28 14:01 UTC
