### ISSUE TITLE
Error Sport365

### ISSUE THREAD

**Issue by Jojo31780** [bugatsinho/bugatsinho.github.io#47] opened 2020-02-18 17:53 UTC
Hi, many thanks for that great addon.
I very frustated because at least 2 months ago all was working well. And know when i want to open a link i have the message Error sport 365 consult journal history for more informations.
I am using kodi 17.6 
Firestick tv
Sport365 version 2.6.10.1
Could you help me please? 
Thanks a lot.

**Comment by bugatsinho** [comment] 2020-02-18 17:59
you know things change fast in kodi! so find another addon. thank you...and try to read before open issues
Duplicate of #45

**Closed by bugatsinho** 2020-02-18 17:59 UTC

**Comment by Jojo31780** [comment] 2020-02-18 18:16
> you know things change fast in kodi! so find another addon. thank you
> Duplicate of #45

Could you advise me a new one please?

**Comment by bugatsinho** [comment] 2020-02-18 18:25
no idea

**Comment by hugoduraes** [comment] 2020-03-06 22:26
@bugatsinho does that mean there won't be updates for this plugin from now on?
