### ISSUE TITLE
Your great but suspect that rlsbb is not playing well with others

### ISSUE THREAD

**Issue by Pawman63** [bugatsinho/bugatsinho.github.io#52] opened 2020-05-03 10:50 UTC
Error whenever you try to open any dir in rlsbb addon it's been quite regular as a situation for a while now. Even when it is working there are regular loops something went wrong and you have to reclick the link.
I know this is not your work it appears to be constantly the site trying to block access.

**Comment by bugatsinho** [comment] 2020-05-09 01:35
Duplicate of #49

**Closed by bugatsinho** 2020-05-09 01:35 UTC
Labels: duplicate
